// <auto-generated />
namespace GCP_CF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialProd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialProd));
        
        string IMigrationMetadata.Id
        {
            get { return "201911180107298_initialProd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
